version: '3.1'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: always
    ports:
      - 8080:8080
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - C:\keycloak_themes:/opt/keycloak/themes