version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: adminer
      POSTGRES_PASSWORD: adminer

  adminer:
    image: adminer
    restart: always
    ports:
      - 7070:8080